name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    #env:
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node.js to ver. 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'

      - name: Install dependencies for Vue.js
        run: npm install --prefix vue

      - name: Build and test Vue.js
        run: npm run build --prefix vue

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'

      - name: Set up Python environment
        run: python -m venv Flask/venv
                
      - name: Activate Python environment
        run: source Flask/venv/bin/activate

      - name: Install Python dependencies for Flask
        run: pip install -r Flask/requirements.txt

      # - name: Test Flask application
      #   run: python Flask/app.py test

      # - name: Run end-to-end tests (if applicable)
      #   run: # Add command to run end-to-end tests (e.g., Cypress, Selenium)
